project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false
  eval: true
  
book:
  title: "Predicting Housing Prices"
  author:
    - Katherine Chen (sc5650)
  repo-url: https://github.com/Katherinechen001/new-temp
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - objective.qmd
    - data overview.qmd
    - methodology.qmd
    - data.qmd
    - chapter21.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


