# Data Overview
The data used in this project is called “ Housing. csv”, sourced from Kaggle. It describes a data record on 545 homes with 13 variables that consist of a mixture of predictive numeric and categorical attributes to describe the features of the homes. The target variable is price, the sale price of each house. 

## Feature Description
<table style="width:100%; border-collapse: collapse;">
  <thead>
    <tr>
      <th style="text-align: left; width: 20%;">Feature</th>
      <th style="text-align: left; width: 20%;">Type</th>
      <th style="text-align: left; width: 60%;">Description</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>price</td><td>Numeric</td><td>Selling price of the house (target variable)</td></tr>
    <tr><td>area</td><td>Numeric</td><td>Size of the house in square feet</td></tr>
    <tr><td>bedrooms</td><td>Numeric</td><td>Number of bedrooms</td></tr>
    <tr><td>bathrooms</td><td>Numeric</td><td>Number of bathrooms</td></tr>
    <tr><td>stories</td><td>Numeric</td><td>Number of stories (floors)</td></tr>
    <tr><td>mainroad</td><td>Cat.</td><td>Whether the house is connected to the main road (Yes/No)</td></tr>
    <tr><td>guestroom</td><td>Cat.</td><td>Presence of a guest room (Yes/No)</td></tr>
    <tr><td>basement</td><td>Cat.</td><td>Presence of a basement (Yes/No)</td></tr>
    <tr><td>hotwaterheating</td><td>Cat.</td><td>Availability of hot water heating (Yes/No)</td></tr>
    <tr><td>airconditioning</td><td>Cat.</td><td>Availability of air conditioning (Yes/No)</td></tr>
    <tr><td>parking</td><td>Numeric</td><td>Number of parking spaces</td></tr>
    <tr><td>prefarea</td><td>Cat.</td><td>Whether the house is in a preferred area (Yes/No)</td></tr>
    <tr><td>furnishingstatus</td><td>Cat.</td><td>Furnishing status (e.g., furnished, semi-furnished, unfurnished)</td></tr>
  </tbody>
</table>

## Initial Observations 
The data, including binary, and multi-class which are pre-processed to be suitable for modeling. No missing values were detected in the dataset, and hence analysis should be straightforward. The variable area would seem to be most obviously related to cost, as it is known that larger properties are more expensive.